#!/bin/bash
#SBATCH --account=erf
#SBATCH --time=1:30:00
#SBATCH --job-name=RisingThermalBubble_ref_soln
#SBATCH --ntasks=256
#SBATCH --mail-user eliot.quon@nrel.gov
#SBATCH --mail-type BEGIN,END,FAIL

# load environment
. ~/.bash_profile
erf-env

srun -n $SLURM_NTASKS --cpu_bind=cores ./rising_thermal_bubble inputs_refsoln &> log
